/*
 * Automatically generated by jrpcgen 1.1.1 on 30.01.15 12:25
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package tests.org.acplt.oncrpc.jrpcgen;
import org.acplt.oncrpc.*;
import java.io.IOException;

public class SimpleTree implements XdrAble {

    public TREE2 value;

    public SimpleTree() {
    }

    public SimpleTree(TREE2 value) {
        this.value = value;
    }

    public SimpleTree(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        value.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = new TREE2(xdr);
    }

}
// End of SimpleTree.java
